name: Deploy Cloud Function
on:
  push:
    branches: [ main ]
env:
  PROJECT: nonprod-apigee-svc-3qph

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      
    steps:
      - uses: actions/checkout@v4

      - name: Google Auth
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{env.PROJECT}}
          token_format: "access_token"
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA }}

      - name: deploy cloud function
        id: deploy
        uses: google-github-actions/deploy-cloud-functions@v3
        with:
          name: MyFunction
          runtime: java11
          project_id: ${{ env.PROJECT }}
          entry_point: functions.MyFunction

      - name: make the url aunthenticated
        run: |
          gcloud functions add-iam-policy-binding MyFunction --member="allUsers" --role="roles/cloudfunctions.invoker"

      - name: test the url
        run: curl "${{ steps.deploy.outputs.url }}"
