name: Deploy Cloud Function
on:
  push:
    branches: [ main ]
env:
  PROJECT: nonprod-apigee-svc-3qph

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Google Auth
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{env.PROJECT}}
          token_format: "access_token"
          create_credentials_file: true
          workload_identity_provider: "projects/748025471373/locations/global/workloadIdentityPools/wip-github/providers/oidc-github"
          service_account: "sa-cloud-function-deploy@nonprod-apigee-svc-3qph.iam.gserviceaccount.com"

      - name: deploy cloud function
        id: deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: MyFunction
          runtime: java11
          project_id: nonprod-apigee-svc-3qph
          entry_point: functions.MyFunction

      - name: make the url aunthenticated
        run: |
          gcloud functions add-iam-policy-binding MyFunction --member="allUsers" --role="roles/cloudfunctions.invoker"

      - name: test the url
        run: curl "${{ steps.deploy.outputs.url }}"
